[workspace]

members = [
    # binaries
    "b64",
    "crc16",
    "cutr",
    "kennard-stone",
    "mp4tag",
    "nom_word_boundary",
    "cnum",
    "sha",
    "tok",
    "utf8char",
    "uuids",

    # libraries
    "general",
    "tokenize",
]
