[workspace]

members = [
    # binaries
    "b64",
    "cutr",
    "kennard-stone",
    "nom_word_boundary",
    "num",
    "sha",
    "tok",
    "utf8char",
    "uuid",

    # libraries
    "general",
    "tokenize",
]
