[workspace]

members = [
    # binaries
    "b64",
    "crc16",
    "cutr",
    "kennard-stone",
    "mp4tag",
    "nom_word_boundary",
    "cnum",
    "sha",
    "tok",
    "utf8char",
    "uuids",

    # libraries
    "general",
    "tokenize",
]

[workspace.dependencies]
anyhow = "1"
clap = { version = "4.3.8", features = ["cargo", "derive"] }
general = { path = "general" }
lazy_static = "1.4"
regex = "1.7"
tokenize = { path = "tokenize" }
