[package]
description = "Display the optauth URI from a QR image"
name = "qr-otpauth"
version = "0.1.0"
authors = ["Dave Farnham <dave.farnham@icloud.com>"]
categories = ["command-line-utilities"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
general = { workspace = true }
image = "0.24"
rqrr = "0.6"
